Implements iter_mut for LruMap
koute/schnellru pull request #5
Opened 2024-05-09 15:54 UTC by anujmax

Implements iter_mut for LruMap, we needed this to be able to mutate the values while iterating. Discussion here: 

https://github.com/subspace/subspace/pull/2736/files#r1595217002

2024-05-10 05:01 UTC, koute requested changes

2024-05-10 05:01 UTC, koute commented on src/lib.rs
> +    map: &'a RawTable<Entry<K, V, L::LinkType>>,
```suggestion
    map: &'a mut RawTable<Entry<K, V, L::LinkType>>,
```

2024-05-10 05:01 UTC, koute commented on src/lib.rs
> +impl<'a, K, V, L> Iterator for IterMut<'a, K, V, L>
Also implement `DoubleEndedIterator` and `ExactSizeIterator` like it is for `Iter`.

2024-05-10 05:01 UTC, koute commented on src/lib.rs
> +        let vec = vec!["D", "C", "B", "A"];
Using `Vec`s as values kinda overcomplicates this test. Can you just use normal integers as values? (And for modifying the values you could e.g. multiply only even values, or something like that.)

2024-05-10 05:01 UTC, koute commented on src/lib.rs
> +            remaining: len,
Stylistic nit.

```suggestion
        let newest = self.newest;
        let remaining = self.len();
        IterMut {
            map: &mut self.map,
            newest,
            remaining,
```

2024-05-10 05:01 UTC, koute commented on src/lib.rs
> +    use core::usize;
Why is this extra import here?

2024-05-14 01:36 UTC, anujmax commented
Hi @koute , could you please help review again.

2024-05-14 06:35 UTC, koute approved these changes
Thanks!

2024-05-14 06:35 UTC, merged

2024-05-14 06:40 UTC, koute commented
Published as 0.2.3